apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-networkpolicy-workaround.yaml
  - 02-podmonitor.yaml
  - 03-recordingrule.yaml
  - 04-scrapeconfig.yaml
  - 05-gpu-utilization.yaml
  - 06-custom-dashboard.yaml
